# Generated by Django 5.0.2 on 2024-02-22 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="captions",
            new_name="caption",
        ),
    ]
